
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PatientBillingSystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Bed_Allocation
{

    public int Allocation_No { get; set; }

    public Nullable<int> Patient_ID { get; set; }

    public string Patient_Name { get; set; }

    public string Ward_Aolloted { get; set; }

    public Nullable<int> Bed_Aolloted { get; set; }

}

}
