
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PatientBillingSystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Beds_Available
{

    public int service_No { get; set; }

    public string ward { get; set; }

    public int bedNo { get; set; }

    public string bed_Availability { get; set; }

}

}
