

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PatientBillingSystem.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class dbPatientBillingEntities6 : DbContext
{
    public dbPatientBillingEntities6()
        : base("name=dbPatientBillingEntities6")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Beds_Available> Beds_Available { get; set; }

}

}

