

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PatientBillingSystem.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class dbPatientBillingEntities2 : DbContext
{
    public dbPatientBillingEntities2()
        : base("name=dbPatientBillingEntities2")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Operatortbl> Operatortbls { get; set; }

}

}

