//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientBillingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Doc_Available
    {
        public int Doctor_No { get; set; }

        [DisplayName("Doctor Id")]
        public int Doctor_ID { get; set; }

        [DisplayName("Name")]
        public string Doctor_Name { get; set; }

        [DisplayName("Doctors Available")]
        public string Doc_Availability { get; set; }
    }
}
