//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientBillingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Doctortbl
    {

        public int Doctor_ID { get; set; }

        [DisplayName("Name")]
        [Required(ErrorMessage = "This field is required")]
        public string Doctor_Name { get; set; }

        [DisplayName("Gender")]
        [Required(ErrorMessage = "This field is required")]
        public string Gender { get; set; }

        [DisplayName("Phone No")]
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "This field is required")]
        public long PhoneNo { get; set; }

        [DisplayName("Email")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "This field is required")]
        public string D_email { get; set; }

        [DisplayName("Specialization")]
        [Required(ErrorMessage = "This field is required")]
        public string specialization { get; set; }

        [DisplayName("Consultation Fee")]
        [Required(ErrorMessage = "This field is required")]
        public Nullable<decimal> Consultation_Fee { get; set; }

        [DisplayName("User Type")]
        [Required(ErrorMessage = "This field is required")]
        public int userType { get; set; }

        [DisplayName("User Name")]
        [Required(ErrorMessage = "This field is required")]
        public string D_userName { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "This field is required")]
        [DataType("Password")]
        public string D_Password { get; set; }
    }
}