//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientBillingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Patienttbl
    {
        public int Patient_ID { get; set; }

        [DisplayName("Name")]
        [Required(ErrorMessage = "This Field is Required")]
        public string Patient_Name { get; set; }

        [DisplayName("Gender")]
        [Required(ErrorMessage = "This Field is Required")]
        public string Gender { get; set; }

        [DisplayName("Age")]
        [Required(ErrorMessage = "This Field is Required")]
        public short Age { get; set; }

        [DisplayName("Bloodgroup")]
        [Required(ErrorMessage = "This Field is Required")]
        public string Bloodgroup { get; set; }

        [DisplayName("Phone No")]
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "This Field is Required")]
        public long PhoneNo { get; set; }

        [DisplayName("Email")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "This Field is Required")]
        public string P_email { get; set; }

        [DisplayName("Address")]
        [Required(ErrorMessage = "This Field is Required")]
        public string P_address { get; set; }

        [DisplayName("Patinent Status")]
        [Required(ErrorMessage = "This Field is Required")]
        public string P_Status { get; set; }

        [DisplayName("User Type")]
        [Required(ErrorMessage = "This Field is Required")]
        public int userType { get; set; }

        [DisplayName("User Name")]
        [Required(ErrorMessage = "This Field is Required")]
        public string userName { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "This Field is Required")]
        [DataType("Password")]
        public string P_Password { get; set; }

        //[DisplayName("Confirm Password  ")]
        //[DataType("Password")]
        //[Compare("P_Password")]
        //public string Confirmpassword { get; set; }
    }
}