//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientBillingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class servicesofferedtbl
    {
        public int Service_ID { get; set; }

        [DisplayName("Service")]
        [Required(ErrorMessage ="This field is required")]
        public string Service_Description { get; set; }

        [DisplayName("Cost Of Service")]
        [Required(ErrorMessage = "This field is required")]
        public decimal Cost_Of_Service { get; set; }
    }
}
