//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientBillingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class usertbl
    {
        //private type_user _userType;

        [DisplayName("User Name  ")]
        [Required(ErrorMessage = "This field is required")]
        public string userName { get; set; }

        [DisplayName("User Type  ")]
        [Required(ErrorMessage = "This field is required")]
        public int userType { get; set; }

        [DisplayName("Password  ")]
        [DataType("Password")]
        [Required(ErrorMessage = "This field is required")]
        public string userpassword { get; set; }

        //public string LoginErrormsg { get; set; }

        //[DisplayName("Confirm Password  ")]
        //[DataType("Password")]
        //[Compare("userpassword")]
        //[Required(ErrorMessage = "This field is required")]
        //public string Confirmpassword { get; set; }

        /*public type_user userType { get => _userType; set => _userType = value; }*/
    }

}